### ISSUE TITLE
RPC connection issue with sending TX

### ISSUE THREAD

**Issue by mvozzo** [PIVX-Project/PET4L#10]
Hello PET4L team, I am encountering an RPC connection issue within PET4L after approving a transaction on my Ledger Nano. 
I am connected to the losangeles.randomzebra.party PIVX Server, but the error message I get...
"err: (unable to send TX - connection to RPC server lost.)"
 
I also tried the amsterdam.randomzebra.party server and I get the same results.  I was unable to connect to the Singapore.randomzebra.party server.

I presume this issue may be associated with the recent PIVX protocol upgrade due to the recent attack, hence you code may need to be upgraded along with the PIVX-SPMT see https://github.com/PIVX-Project/PIVX-SPMT/issues/39  (this may help perhaps?)  

Can someone please fix this issue soon as I'd like to move some of my PIV coins off my Ledger Nano?  Thank you.

**Comment by random-zebra** [comment]
Hi @mvozzo . Yes, a new release will be out soon.

In the meantime, you can use this workaround.
When PET4L shows (after the signature) the confirmation dialog, asking if you want to broacast the signed transaction, you click "no".
Then look in the Console log. You should have the log:
```
Raw signed transaction:
<--- long hex string --->
Amount to send: N
```

Copy `<--- long hex string --->`, and use it to broadcast the tx from any PIVX wallet, with the rpc command `sendrawtransaction`. 
If you don't have a PIVX core wallet, you can also broadcast the transaction from the explorer, at this link: https://explorer.pivx.link/sendtx

**Comment by marvelloz** [comment]
Thank you @random-zebra , your clear instructions helped my transfer some PIV. 
Thanks again for working on PET4L, it's an awesome tool for us hardware wallet PIVX holders :-)
