### ISSUE TITLE
Transparent (De-Shield Tx in Nano-S) to Transparent Tx Error in PET4L

### ISSUE THREAD

**Issue by GeniusWizard** [PIVX-Project/PET4L#14]
Send Pivx Transparent (De-Shield Tx in Nano-S) to Transparent Address Error in PET4L
Please check this issue.

2021-09-27 13:33:56 : Preparing transaction. Please wait...
2021-09-27 13:33:56 : HW: Preparing transfer TX
EXCEPTION
caller : process_ledger_exceptions_int
function : prepare_transfer_tx_bulk
err: bytearray index out of range
===> Ledger - generic exception
2021-09-27 13:33:56 : Closing LEDGER client
EXCEPTION
caller : func_int
function : prepare_transfer_tx_bulk
err: Ledger - generic exception
===> Ledger - generic exception
2021-09-27 13:34:02 : Closing LEDGER client

**Comment by random-zebra** [comment]
tracking in #15
