### ISSUE TITLE
This Windows version (6.0.6000) does not support the required Bluetooth API

### ISSUE THREAD

**Issue by AdonisPhusis** [PIVX-Project/PET4L#7]
I am happy to have successfully launched my stacking with my ledger. now i need to correct this error : 

This Windows version (6.0.6000) does not support the required Bluetooth API. Consider updating to a more recent Windows (10.0.10586 or above).

it's when i launch PET4L
i use windows server 2012 RC2

how can i fix this
thank you so much

**Comment by random-zebra** [comment]
Hi @AdonisPhusis thanks for reporting this.
It seems that PyQT 5.10 is incompatible with older windows versions. I would recommend updating to more recent Windows, or alternatively trying to run the tool from the sources with PyQT 5.9 installed. If you don't know how to run from sources, I can prepare a pre-release binary executable file for you to test.

**Comment by AdonisPhusis** [comment]
I would like the pre-release binary executable file so that I can test it. If I can get out my staking I would install linux. thank you

**Comment by random-zebra** [comment]
@AdonisPhusis I've uploaded a version compiled with PyQt-5.9 here <https://github.com/PIVX-Project/PET4L/releases/tag/v0.1.0-c>
Not sure if it works on windows server 2012 RC2, as I have not a system with it to test (it does work on Win7 though).

**Comment by AdonisPhusis** [comment]
It works. great job ... i will invest in new masternodes considering the quality of the community developers!
